[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  # Example: set environment variables here or configure them in the Netlify UI
  # GEMINI_API_KEY = "${GEMINI_API_KEY}"
